# Generated by Django 4.0 on 2021-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_vacationlist_target_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationlist',
            name='add_date',
            field=models.IntegerField(),
        ),
    ]
