# Generated by Django 4.0 on 2021-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_vacationlist_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationuse',
            name='end_date_afternoon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacationuse',
            name='end_date_morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacationuse',
            name='start_date_afternoon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacationuse',
            name='start_date_morning',
            field=models.BooleanField(default=True),
        ),
    ]
