# Generated by Django 4.0 on 2021-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vacationuse_end_date_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationlist',
            name='add_date',
            field=models.FloatField(),
        ),
    ]
