# Generated by Django 4.0 on 2021-12-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_vacationlist_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationuse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter_2', to='users.user'),
        ),
    ]
