# Generated by Django 4.0 on 2021-12-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_vacationuse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationuse',
            name='accepter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepter_2', to='users.user'),
        ),
        migrations.AlterField(
            model_name='vacationuse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VacationList', to='users.vacationlist'),
        ),
    ]
