# Generated by Django 4.0 on 2021-12-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_vacationuse_accepter_1_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationuse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VacationList', to='users.user'),
        ),
    ]
