# Generated by Django 4.0 on 2022-01-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_user_car_auth_km_user_car_cc_user_car_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jarvis_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.IntegerField()),
                ('document', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='acceptor_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('priolity', models.IntegerField()),
                ('result', models.IntegerField(default=0)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accpetor_list_user', to='users.user')),
                ('jarvis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jarvis_list_no', to='core.jarvis_list')),
            ],
        ),
    ]
