# Generated by Django 4.0 on 2022-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarvis_list',
            name='document',
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_9',
            field=models.IntegerField(default=0),
        ),
    ]
