# Generated by Django 4.0 on 2022-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_jarvis_list_document_jarvis_list_document_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarvis_list',
            name='document_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jarvis_list',
            name='document_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
