# Generated by Django 4.0 on 2022-01-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_user_car_auth_km_user_car_cc_user_car_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=100)),
                ('witness', models.CharField(max_length=100)),
                ('travel_pay', models.IntegerField()),
                ('traffice_pay', models.IntegerField()),
                ('sleep_pay', models.IntegerField()),
                ('eatandother_pay', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_user', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_pay', models.FloatField(blank=True, null=True)),
                ('hipass_pay', models.IntegerField(blank=True, null=True)),
                ('sleep_pay', models.IntegerField(blank=True, null=True)),
                ('sleep_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('other_pay', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_report_travel', to='groupware.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_report_traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='travel/report/traffic/')),
                ('date', models.DateField(blank=True, null=True)),
                ('km', models.FloatField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=50, null=True)),
                ('end', models.CharField(blank=True, max_length=50, null=True)),
                ('oneway', models.BooleanField(default=False)),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_report', to='groupware.travel_report')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_report_sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='travel/report/sleep/')),
                ('date', models.DateField(blank=True, null=True)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_report', to='groupware.travel_report')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_report_other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='travel/report/other/')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('pay', models.IntegerField(blank=True, default=0, null=True)),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_report', to='groupware.travel_report')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_report_hipass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='travel/report/hipass/')),
                ('date', models.DateField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=50, null=True)),
                ('end', models.CharField(blank=True, max_length=50, null=True)),
                ('pay', models.IntegerField(blank=True, default=0, null=True)),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipass_report', to='groupware.travel_report')),
            ],
        ),
    ]
