# Generated by Django 4.0 on 2022-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='eatandother_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
