# Generated by Django 4.0.1 on 2022-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0002_travel_eatandother_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='address',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='location',
            new_name='location_1',
        ),
        migrations.AddField(
            model_name='travel',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='address_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='address_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='location_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='location_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='location_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='location_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='witness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
