# Generated by Django 4.0.1 on 2022-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0003_rename_address_travel_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='km_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='km_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='km_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='km_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='km_5',
            field=models.FloatField(default=0),
        ),
    ]
