# Generated by Django 4.0.1 on 2022-01-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0004_travel_km_1_travel_km_2_travel_km_3_travel_km_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='reback_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='reback_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='reback_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='reback_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travel',
            name='reback_5',
            field=models.BooleanField(default=False),
        ),
    ]
