# Generated by Django 4.0.1 on 2022-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0005_travel_reback_1_travel_reback_2_travel_reback_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='eatandother_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='sleep_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='traffice_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
