# Generated by Django 4.0.1 on 2022-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0006_alter_travel_eatandother_pay_alter_travel_sleep_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='total_km',
            field=models.FloatField(default=0),
        ),
    ]
