# Generated by Django 4.0.1 on 2022-01-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupware', '0008_alter_travel_km_2_alter_travel_km_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_report_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='travel/report/food/')),
                ('date', models.DateField(blank=True, null=True)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_report', to='groupware.travel_report')),
            ],
        ),
    ]
