# Generated by Django 4.0 on 2021-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('product_name_in', models.CharField(blank=True, max_length=120, null=True)),
                ('product_name_out', models.CharField(blank=True, max_length=120, null=True)),
                ('product_size', models.CharField(blank=True, max_length=20, null=True)),
                ('product_count', models.CharField(blank=True, max_length=20, null=True)),
                ('product_init_count', models.FloatField(blank=True, null=True)),
                ('product_init_price_in', models.FloatField(blank=True, null=True)),
                ('product_vat_in', models.BooleanField(default=False)),
                ('product_init_price_out', models.FloatField(blank=True, null=True)),
                ('product_vat_out', models.BooleanField(default=False)),
                ('product_group', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
